sonar.organization=gradion
sonar.projectKey=gradionai_acdc-poc
sonar.sources=server/src
sonar.tests=server/test
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
sonar.exclusions=**/dist/**,e2e/**,**/*.config.*
